apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-backend-blue
  namespace: recipe-app
  labels:
    app: recipe-backend
    slot: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-backend
      slot: blue
  template:
    metadata:
      labels:
        app: recipe-backend
        slot: blue
    spec:
      containers:
        - name: backend
          image: ACRNAMEHERE.azurecr.io/recipe-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: MONGO_DB_NAME
              value: ead_ca2
            - name: MONGO_COLLECTION
              value: ead_2024
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15