apiVersion: v1
kind: Service
metadata:
  name: recipe-backend
  namespace: recipe-app
spec:
  selector:
    app: recipe-backend
    slot: blue
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-frontend
  namespace: recipe-app
spec:
  type: LoadBalancer
  selector:
    app: recipe-frontend
    slot: blue
  ports:
    - port: 80
      targetPort: 22137